networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./run_server
    depends_on:
      - postgres
    networks:
      - dev

  frontend:
    build:
      context: ./static
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgres
    networks:
      - dev