networks:
  dev:

services:
  backend:
    build:
      context: ./run_server
    depends_on:
      - postgres
    networks:
      - dev

  frontend:
    build:
        ports:
      - "8080:8080"
      context: ./static
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgres
    networks:
      - dev