global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'infotech_app'
    static_configs:
      - targets: ['host.docker.internal:8000']  
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
